In [12]:
import numpy as np
#a1=np.array([2,4,3,5,6])
a1=np.array([[2,3,4],[3,4,5]])
a1

array([[2, 3, 4],
       [3, 4, 5]])

In [8]:

a2=np.array([[2,3,4],[3,4,5]])
a2

array([[2, 3, 4],
       [3, 4, 5]])

In [9]:
a3=np.array([2,3,67.8])
a3

array([ 2. ,  3. , 67.8])

In [10]:
a2.ndim

2

In [11]:
a1.ndim

1

In [13]:
a2.dtype

dtype('int64')

In [14]:
a2.size

6

In [15]:
a2.itemsize

8

In [16]:
a2.shape

(2, 3)

In [19]:
a4=np.zeros((2,3))
a4

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
a5=np.ones((2,3))
a5

array([[1., 1., 1.],
       [1., 1., 1.]])

In [22]:
a6=np.array([1,2,3],dtype=int) # also use float and bool
a6

array([1, 2, 3])

In [23]:
a7=np.arange(-2,24,2) #start stop step
a7

array([-2,  0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [24]:
#arthmetic operations performed on numpy:-
a1=np.array([[1,2,3],[4,5,6]])
a1


array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
a2=np.array([[10,20,30],[40,50,60]])
a2

array([[10, 20, 30],
       [40, 50, 60]])

In [26]:
 #addition
a1+a2

array([[11, 22, 33],
       [44, 55, 66]])

In [28]:
#subtraction
a2-a1

array([[ 9, 18, 27],
       [36, 45, 54]])

In [29]:
#multiplication
a1*a2

array([[ 10,  40,  90],
       [160, 250, 360]])

In [30]:
#division
a2/a1

array([[10., 10., 10.],
       [10., 10., 10.]])

In [36]:
a1**2

array([[ 4,  9],
       [ 9, 16],
       [25, 49]])

In [41]:
#for matrix multiplication
a1=np.array([[2,3],[3,1],[5,7]])
a1

array([[2, 3],
       [3, 1],
       [5, 7]])

In [33]:
a2=np.array([[3,4,5],[5,7,6]])
a2

array([[3, 4, 5],
       [5, 7, 6]])

In [34]:
a1@a2

array([[21, 29, 28],
       [29, 40, 39],
       [50, 69, 67]])

In [38]:
#transpose operations
a1.transpose()

array([[2, 3, 5],
       [3, 4, 7]])

In [42]:
a1.sort()
a1

array([[2, 3],
       [1, 3],
       [5, 7]])

In [5]:
import numpy as np
a6=np.array([[5,7,2],[6,4,1]])
a6

array([[5, 7, 2],
       [6, 4, 1]])

In [6]:
a6.sort(axis=0) 
a6

array([[5, 4, 1],
       [6, 7, 2]])

In [7]:
a6.sort(axis=1)
a6

array([[1, 4, 5],
       [2, 6, 7]])

In [9]:
a6.reshape(3,2) #reshaped ad 3X2 matrix

array([[1, 4],
       [5, 2],
       [6, 7]])

In [10]:
#statistical operations performed on numpy
a6

array([[1, 4, 5],
       [2, 6, 7]])

In [11]:
a6.min()

np.int64(1)

In [12]:
a6.min(axis=0) #col wise min element

array([1, 4, 5])

In [14]:
a6.min(axis=1) #row wise min element

array([1, 2])

In [15]:
a6.max()

np.int64(7)

In [16]:
a6.max(axis=0)

array([2, 6, 7])

In [17]:
a6.max(axis=1)

array([5, 7])

In [18]:
a6.sum()


np.int64(25)

In [19]:
a6.mean()

np.float64(4.166666666666667)

In [21]:
a6.std() #standard deviation

np.float64(2.1147629234082532)

In [22]:
a6[0,1]

np.int64(4)

In [ ]:
# 1) create a 3D array and axis its elements using index .
# 2) create a 2D array and perform all the arithmetic and statistical operations on the array.
# 3) create a 2D array and perform the operations transpose,sort,reshape.
# 4) practice other ways of creating the arrays.